name = "BplusCore"
uuid = "1fb136ff-715c-473e-9ae1-0caef0ff09b1"
authors = ["William Mishra-Manning <manning.w27@gmail.com>"]
version = "0.2.2"

[deps]
BitFlags = "d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
julia="1.9"
BitFlags="0.1"
JSON3="1.14"
MacroTools="0.5.13"
NamedTupleTools="0.14"
Setfield="1.1"
StaticArrays="1.8"
StructTypes="1.10"
TupleTools="1.4"